name = "worker-auth"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-30"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "d1-auth"
database_id = "1357668b-3fdf-4b91-b618-63191d8eb37f"

[observability]
enabled = true
